#pragma once

#define RESOURCE_DIR_NAME "resources\\"
#define DEFAULT_FONT_PATH "C:/Windows/Fonts/consola.ttf"

#define FONT_SIZE 25

#define MIN_SCALE 0.05f
#define MAX_SCALE 20.f

#define TEXTURE_ICONS_IDX 0

#define PROJECT_EXT ".mlp"
#define PROJECT_EXT_NAME "mlp"
#define SCHEMATIC_SHEET_EXT ".mls"
#define SCHEMATIC_SHEET_EXT_NAME "mls"

#define GUID_STRING_SIZE 38
#define CLIPBOARD_COPY_IDENTIFICATION "[A8ECDC3F-A527-45BB-8AEC-9D19EC0BA190]"
#define CLIPBOARD_CUT_IDENTIFICATION  "[BBE7BD64-510B-4A27-85EF-A74204089557]"